analysis/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('<str:id>/<str:nama>/<int:bulan1>/<int:bulan2>/<int:tahun>', analyst, name='analysis')
]

home/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView
from stream_tweet.views import create_stream

urlpatterns = [
    path('', HomeView.as_view()),
    path('<int:page>', HomeView.as_view(), name='home'),
    path('manage/', manage, name='manage'),
    path('update/<str:id>/', update, name='update'),
    path('delete/<str:id>/', delete, name='delete'),
    path('detail/<str:id>/', detail, name='detail')
]

show/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('<str:id>/<str:nama>/<int:bulan1>/<int:bulan2>/<int:tahun>', show_data, name='show')
]

twitter_topic_analyst/urls.py
from stream_tweet import views
from show.views import download_data
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/home')),
    path('home/', include(('home.urls', 'home'), namespace='home')),
    path('analysis/', include(('analysis.urls', 'analysis'), namespace='analysis')),
    path('stream_tweet/', include(('stream_tweet.urls', 'stream_tweet'), namespace='stream')),
    path('show/', include(('show.urls','show'), namespace='show')),
    path('download/<str:id>/<str:nama>/<int:bulan1>/<int:bulan2>/<int:tahun>', download_data, name='download'),
    path('admin/', admin.site.urls)
]

home/models.py
from django.db import models
import uuid

# Create your models here.
class IsuTweet(models.Model):
    id_ref          = models.CharField(primary_key=True, default=uuid.uuid4, editable=False, max_length=50)
    judul           = models.CharField(max_length=15)
    deskripsi       = models.TextField(blank=True)
    tanggal_buat    = models.DateField(auto_now_add=True)
    keyword         = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.judul} at {self.tanggal_buat}'

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import ListView
from stream_tweet.models import TweetsModel, Hashtag
from .models import IsuTweet
from stream_tweet import stream
from django.db.models import Count
from sklearn.ensemble import IsolationForest
import numpy as np

class HomeView(ListView):
    model = IsuTweet
    template_name = "home/home.html"
    context_object_name = "isu_list"
    ordering = ['-tanggal_buat']
    paginate_by = 5


def manage(request):
    return render(request, 'home/manage.html', {'isu_list':IsuTweet.objects.all()})


def update(request, id):
    if request.method == 'POST':
        IsuTweet.objects.filter(id_ref=id).update(
            judul       = request.POST["judul"],
            deskripsi   = request.POST["deskripsi"],
            keyword     = request.POST["keyword"]
            )
        return HttpResponseRedirect('/home/manage')
    else:
        return render(request, 'home/update.html', {'isu':IsuTweet.objects.get(id_ref=id)})


def delete(request, id):
    if request.method == 'POST':
        if id in request.POST:
            IsuTweet.objects.get(id_ref=id).delete()
            TweetsModel.objects.filter(id_isu=id).delete()
        return HttpResponseRedirect('/home/manage')
    else:
        return render(request, 'home/delete_confirmation.html', {'isu':IsuTweet.objects.get(id_ref=id)})

def std_outlier(data, threshold=2):
    mean = np.mean(data)
    std = np.std(data)
    return mean+(threshold*std), mean-(threshold*std)

def detail(request, id):
    tweet_id = TweetsModel.objects.filter(id_isu=id).exclude(tags=None)
    hashtag_list = [[h['tags__hashtag'], Hashtag.objects.get(hashtag=h['tags__hashtag']).jumlah, h['tags__hashtag__count']] for h in tweet_id.values('tags__hashtag').annotate(Count('tags__hashtag')).order_by('-tags__hashtag__count') if h['tags__hashtag']!=None]
    zipHashList = list(zip(*hashtag_list))
    appearance = np.array(zipHashList[1])
    batas = std_outlier(appearance[appearance>0])
    print(batas)
    hashtag_list = list(zip(zipHashList[0], zipHashList[1], zipHashList[2], [1 if (i>batas[0] or i<batas[1] and i!=0) else 0 for i in zipHashList[1]]))
    tweet_like = tweet_id.order_by('-like_count')
    tweet_retweet = tweet_id.order_by('-retweet_count')
    tweet_reply = tweet_id.order_by('-reply_count')
    mul = [[i.like_count, i.retweet_count] for i in tweet_id]
    iso = IsolationForest(random_state=27).fit_predict(mul)
    outlierId = [tweet_id[i].id_tweet for i in range(len(tweet_id)) if iso[i]==1]

    konteks = { 'hashtag_list':hashtag_list,
                'tweet_list':list(zip(
                        zip(tweet_like[:5], tweet_like.values('tags__hashtag')[:5]),
                        zip(tweet_retweet[:5], tweet_retweet.values('tags__hashtag')[:5]),
                        zip(tweet_reply[:5], tweet_reply.values('tags__hashtag')[:5])
                        )),
                'outlier':outlierId,
                'isu':IsuTweet.objects.get(id_ref=id),
                'tweet':tweet_id.order_by('-waktu')}

    return render(request, 'home/detail.html', konteks)

home/templates/home/delete_confirmation.html
{% extends "base.html" %}

{% block judul_halaman %}
	Delete
{% endblock %}

{% block isi %}
	<h1>Delete Confirmation</h1>
	<p>Apakah benar anda ingin menghapus isu berikut:</p>
	<h2>{{isu.judul}}</h2>
	<p>{{isu.tanggal_buat}}</p>
	<p>{{isu.deskripsi}}</p>
	<form method='POST'>
		{% csrf_token %}
		<button type="submit" class="btn btn-outline-primary" name={{isu.id_ref}}>Ya</button>
		<a class="btn btn-outline-danger" href="{% url 'home:manage' %}">Tidak</a>
	</form>
{% endblock %}

home/templates/home/detail.html
{% extends "base.html" %}

{% block judul_halaman %}
  Detail - {{isu.judul}}
{% endblock %}

{% block isi %}
  <div class="row">
    <table>
      <thead>
        <tr>
          <th style="width:200px"><h1>{{isu.judul}}</h1></th>
          <th style="width:365px"><h4>Keyword:</h4></th>
          <th></th>
          <th><h4>Deskripsi:</h4></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><h5>{{isu.tanggal_buat}}</h5></td>
          <td><h5>{{isu.keyword|truncatechars:90}}</h5></td>
          <td></td>
          <td><h5>{{isu.deskripsi|truncatechars:200}}</h5></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="row">
  <br>
  </div>

  <div class="row">
    <div class="col">
      <table id="hashtag_table" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
    	  <thead class="thead-dark">
    	    <tr>
    	      <th scope="col">#</th>
    	      <th scope="col">Hashtag</th>
            <th scope="col">Terakhir Muncul</th>
    	      <th scope="col">Jumlah</th>
    	    </tr>
    	  </thead>
    	  <tbody>
    	    {% for hashtag in hashtag_list %}
      	    <tr>
      	      <th scope="row" height="25px">{{forloop.counter}}</th>
              {% if hashtag.3 == 1 %}
                <td><a href="{% url 'analysis:analysis' isu.id_ref hashtag.0 0 0 0 %}" style="color: #8ebf42">{{hashtag.0}}</a></td>
              {% else %}
                <td><a href="{% url 'analysis:analysis' isu.id_ref hashtag.0 0 0 0 %}">{{hashtag.0}}</a></td>
              {% endif %}
      	      <td>{{hashtag.1}} x</td>
              <td>{{hashtag.2}}</td>
      	    </tr>
    	    {% endfor %}
    	  </tbody>
       </table>
    </div>
    <div class="col">
      <div class="row">
        <table class="table table-hover" style="border:1px solid;">
          <thead class="bg-success">
            <tr>
              <th style="border-right:1px solid">Most Like</th>
              <th style="border-right:1px solid">Most Retweet</th>
              <th style="border-right:1px solid">Most Reply</th>
            </tr>
          </thead>
          <tbody>
            {% for l,rw,rp in tweet_list %}
              <tr>
                <td style="border-right:1px solid">
                  {% if l.id_tweet in outlier %}
                    <a href="{% url 'analysis:analysis' isu.id_ref l.1.tags__hashtag 0 0 0 %}" style="color: #8ebf42" data-toggle="tooltip" data-placement="right" title="{{l.1.tags__hashtag}} | {{l.0.like_count}} liked">
                      @{{l.0.user_id}}
                    </a>
                  {% else %}
                    <a href="{% url 'analysis:analysis' isu.id_ref l.1.tags__hashtag 0 0 0 %}" class="text-dark" data-toggle="tooltip" data-placement="right" title="{{l.1.tags__hashtag}} | {{l.0.like_count}} liked">
                      @{{l.0.user_id}}
                    </a>
                  {% endif %}
                </td>
                <td style="border-right:1px solid">
                  {% if rw.id_tweet in outlier %}
                    <a href="{% url 'analysis:analysis' isu.id_ref rw.1.tags__hashtag 0 0 0 %}" style="color: #8ebf42" data-toggle="tooltip" data-placement="right" title="{{rw.1.tags__hashtag}} | {{rw.0.retweet_count}} retweeted">
                      @{{rw.0.user_id}}
                    </a>
                  {% else %}
                    <a href="{% url 'analysis:analysis' isu.id_ref rw.1.tags__hashtag 0 0 0 %}" class="text-dark" data-toggle="tooltip" data-placement="right" title="{{rw.1.tags__hashtag}} | {{rw.0.retweet_count}} retweeted">
                      @{{rw.0.user_id}}
                    </a>
                  {% endif %}
                </td>
                <td>
                  <a href="{% url 'analysis:analysis' isu.id_ref rp.1.tags__hashtag 0 0 0 %}" class="text-dark" data-toggle="tooltip" data-placement="right" title="{{rp.1.tags__hashtag}} | {{rp.0.reply_count}} replied">
                    @{{rp.0.user_id}}
                  </a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="row"></div>
      <div class="row">
        <div class="container bg-info" style="border:1px solid; height:200px">
          <div id="TweetList" class="carousel slide">
            <div class="carousel-inner">
              <div class="carousel-item active" data-interval="3000">
                <div class="row justify-content-center">
                  <h1>Latest Tweet</h1>
                </div>
                <div class="row justify-content-center" style="margin-top:10px">
                  <button type="submit" class="btn btn-secondary" onclick="window.open('{% url 'show:show' isu.id_ref 'all' 0 0 0 %}','_blank')">Lihat Data</button>
                </div>
                <div class="row justify-content-center" style="margin-top:10px">
                  <button type="button" class="btn btn-success" onclick="window.open('{% url 'download' isu.id_ref 'all' 0 0 0 %}')">Download CSV</button>
                </div>
              </div>
              {% for t in tweet %}
              <div class="carousel-item" data-interval="6000">
                <div class="row">
                  <div class="col"><h2>@{{t.user_id}}</h2></div>
                  <div class="col offset-md-auto"><h3>{{t.waktu}}</h3></div>
                </div>
                <div class="row text-white">
                  <div class="col"><br><br><h5>{{t.teks}}</h5></div>
                </div>
              </div>
              {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#TweetList" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#TweetList" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

home/templates/home/home.html
{% extends "base.html" %}

{% block judul_halaman %}
	Home
{% endblock %}

{% block isi %}
<div class="row">

	<div class="col-md">
		{% if isu_list %}
			<span class="step-links">
				{% if page_obj.has_previous %}
				<a href="{% url 'home:detail' 1 %}">&laquo; first</a>
				<a href="{% url 'home:detail' page_obj.previous_page_number %}">previous</a>
				{% endif %}

				<span class="current">
					Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
				</span>

				{% if page_obj.has_next %}
				<a href="{% url 'home:detail' page_obj.next_page_number %}">next</a>
				<a href="{% url 'home:detail' page_obj.paginator.num_pages %}">last &raquo;</a>
				{% endif %}
			</span>
			{% for isu in isu_list %}
			<h1><a class="text-dark" href="{% url 'home:detail' isu.id_ref %}">{{isu.judul}}</a></h1><h3>{{isu.keyword}}</h3>
			<p>{{isu.tanggal_buat}}</p>
			<p class="border-bottom">{{isu.deskripsi}}</p>
			{% endfor %}
		{% else %}
			<h3>Tidak ada yang bisa ditampilkan</h3>
		{% endif %}
	</div>
</div>

{% endblock %}

home/templates/home/manage.html
{% extends "base.html" %}

{% block judul_halaman %}
  Manage
{% endblock %}

{% block isi %}
<h1>Manage Isu</h1>

<table class="table mt-4">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Judul</th>
      <th scope="col">Deskripsi</th>
      <th scope="col">Created at</th>
      <th scope="col">Action</th>
    </tr>
  </thead>

  <tbody>
    {% for isu in isu_list %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{isu.judul}}</td>
      <td>{{isu.deskripsi|truncatechars:50}}</td>
      <td>{{isu.tanggal_buat}}</td>
      <td>
        <a class="btn btn-warning" href="{% url 'home:update' isu.id_ref %}">Edit</a>
        <a class="btn btn-danger" href="{% url 'home:delete' isu.id_ref %}">Delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>

</table>
{% endblock %}

home/templates/home/update.html
{% extends "base.html" %}

{% block judul_halaman %}
    Update
{% endblock %}

{% block isi %}
	<h1>Update Isu</h1>

	<form method="POST">
		{% csrf_token %}
    <div class="form-group">
      <label for="judul">Judul</label>
      <input id="judul" name="judul" value="{{isu.judul}}" class="form-control" type="text" required="true">
    </div>

    <div class="form-group">
      <label for="desc">Deskripsi</label>
      <textarea rows="3" id="desc" name="deskripsi" class="form-control" type="text">{{isu.deskripsi}}</textarea>
    </div>

    <div class="form-group">
      <label for="key">Keyword (gunakan 'OR' sebagai pemisah keyword)</label>
      <input id="key" name="keyword" value="{{isu.keyword}}" class="form-control" type="text" placeholder="Contoh: televisi OR TV" required="true">
    </div>

		<button type="submit" class="btn btn-warning">Update</button>
		<a href="{% url 'home:manage' %}" class="btn btn-danger">Tidak</a>
	</form>
{% endblock %}