analysis/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('<str:id>/<str:nama>/<int:bulan1>/<int:bulan2>/<int:tahun>', analyst, name='analysis')
]

home/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView
from stream_tweet.views import create_stream

urlpatterns = [
    path('', HomeView.as_view()),
    path('<int:page>', HomeView.as_view(), name='home'),
    path('manage/', manage, name='manage'),
    path('update/<str:id>/', update, name='update'),
    path('delete/<str:id>/', delete, name='delete'),
    path('detail/<str:id>/', detail, name='detail')
]

show/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('<str:id>/<str:nama>/<int:bulan1>/<int:bulan2>/<int:tahun>', show_data, name='show')
]

twitter_topic_analyst/urls.py
from stream_tweet import views
from show.views import download_data
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/home')),
    path('home/', include(('home.urls', 'home'), namespace='home')),
    path('analysis/', include(('analysis.urls', 'analysis'), namespace='analysis')),
    path('stream_tweet/', include(('stream_tweet.urls', 'stream_tweet'), namespace='stream')),
    path('show/', include(('show.urls','show'), namespace='show')),
    path('download/<str:id>/<str:nama>/<int:bulan1>/<int:bulan2>/<int:tahun>', download_data, name='download'),
    path('admin/', admin.site.urls)
]

show/models.py
from django.db import models

# Create your models here.

analysis/views.py
from io import BytesIO
from collections import Counter
from wordcloud import WordCloud
from django.shortcuts import render
from django.db.models import Count, Max
from django_pandas.io import read_frame
from folium.plugins import MarkerCluster
from django.http import HttpResponseRedirect
from stream_tweet.models import TweetsModel, Hashtag
import folium, matplotlib.pyplot as plt, base64, json, numpy as np

def std_outlier(data, out_sign, no_out_sign, threshold=2):
    mean = np.mean(data)
    std = np.std(data)
    return [out_sign if (i>(mean+threshold*std) or i<(mean-threshold*std)) else no_out_sign for i in data]

def marking(data):
    folium.Marker(
        [data.latitude,data.longitude],
        tooltip=f"@{data.user_id} || {data.waktu.strftime('%d/%m/%Y')}",
        icon=folium.Icon(color='blue'),
        popup=data.teks
    ).add_to(marker_cluster)


def analyst(request, id, nama, **kwargs):
    bulan_list = ['januari', 'februari', 'maret', 'april', 'mei', 'juni',
    'juli', 'agustus', 'september', 'oktober', 'november', 'desember']

    if request.method == 'POST':
        bulan1 = bulan_list.index(request.POST['bulan1'].lower())+1
        bulan2 = bulan_list.index(request.POST['bulan2'].lower())+1
        tahun  = request.POST['tahun']
        return HttpResponseRedirect(f'/analysis/{id}/%23{nama[1:]}/{bulan1}/{bulan2}/{tahun}')

    tweet_tag = tweet_tag_unf = TweetsModel.objects.filter(id_isu=id, tags__hashtag=nama)

    b = tweet_tag.dates('waktu','month')
    if kwargs['bulan1']!=0:
        tahun = kwargs['tahun']
        bulan1 = kwargs['bulan1']
        if bulan1 <= kwargs['bulan2']:
            bulan2 = kwargs['bulan2']
            tweet_tag  = tweet_tag.filter(waktu__year=tahun,waktu__month__gte=bulan1,waktu__month__lte=bulan2)
            tweet_date = TweetsModel.objects.filter(waktu__year=tahun,waktu__month__gte=bulan1,waktu__month__lte=bulan2)
        else:
            bulan2 = max(b).month
            tweet_tag  = tweet_tag.filter(waktu__year=tahun,waktu__month__gte=bulan2)
            tweet_date = TweetsModel.objects.filter(waktu__year=tahun,waktu__month__gte=bulan2)
    else:
        bulan1, bulan2 = min(b).month, max(b).month
        tahun = max(tweet_tag.dates('waktu', 'year')).year
        tweet_tag  = tweet_tag.filter(waktu__year=tahun)
        tweet_date = TweetsModel.objects.filter(waktu__year=tahun,waktu__month__gte=bulan1,waktu__month__lte=bulan2)

    date_dict     = tweet_tag.values('waktu').annotate(Count('waktu'))
    date_dict_all = tweet_date.values('waktu').annotate(Count('waktu'))

    out_sign = 'point { size: 7; shape-type: star; fill-color: #a52714; dataOpacity: 0.3; visible: true }'
    no_out_sign = 'point'

    line_data = [[f"{d['waktu'].strftime('%d/%m')}", d['waktu__count'], da['waktu__count']] for d,da in zip(date_dict, date_dict_all)]
    zipHashList = list(zip(*line_data))
    out1,out2 = std_outlier(zipHashList[1], out_sign, no_out_sign), std_outlier(zipHashList[2], out_sign, no_out_sign)
    line_data = list(zip(zipHashList[0], zipHashList[1], zipHashList[2], out1, out2))
    line_data = [list(i) for i in line_data]
    line_data.insert(0,['tanggal', 'tweet dengan hashtag', 'semua tweet', {'type': 'string', 'role': 'style'}, {'type': 'string', 'role': 'style'}])

    f = folium.Figure(width=1000, height=390)
    m = folium.Map(location=(-2,116.5), zoom_start=5, tiles="CartoDB positron")
    global marker_cluster
    marker_cluster = MarkerCluster().add_to(m)

    tweet_lokasi = tweet_tag.exclude(lokasi=None)

    try:    nowhere = tweet_lokasi.count()
    except: nowhere = 0

    data_lokasi = {t['lokasi']:t['lokasi__count'] for t in tweet_lokasi.values('lokasi').annotate(Count('lokasi'))}

    for i in map(marking, list(tweet_lokasi)):pass

    with open('data\indonesia.geojson') as ig:
        json_loc = json.load(ig)

    data_provinsi = {}
    for i,j in enumerate(json_loc['features']):
        if j['properties']['state'] in data_lokasi.keys():
            data_provinsi[j['properties']['state']] = json_loc['features'][i]['properties']['jumlah'] = data_lokasi[j['properties']['state']]
        else:
            json_loc['features'][i]['properties']['jumlah'] = 0

    pmap = folium.Choropleth(
                geo_data=json_loc,
                data=data_lokasi,
                key_on='properties.state',
                fill_color='YlOrRd'
            ).add_to(m)

    folium.features.GeoJsonTooltip(
            fields=['state','jumlah'],
            aliases=['Provinsi','Jumlah'],
            labels=True,
            sticky=True,
            toLocaleString=True).add_to(pmap.geojson)

    folium.plugins.Search(layer=pmap,
                     geom_type='Polygon',
                     placeholder='Cari Provinsi',
                     collapsed=True,
                     search_label='state',
                     weight=3
                    ).add_to(m)

    m.add_to(f)

    with open('data\stopword.txt') as stop:
        stopword = set(stop.read().split('\n'))

    teks_tweet = ' '.join([t.teks for t in tweet_tag])

    wordcloud = WordCloud(random_state=27,
                    height=205,
                    background_color='black',
                    colormap='Set2',
                    collocations=False,
                    stopwords=stopword).generate(teks_tweet)

    fig = plt.figure()
    plt.imshow(wordcloud)
    plt.axis("off")

    tmpfile = BytesIO()
    fig.savefig(tmpfile, format='png', bbox_inches='tight')
    graphic = base64.b64encode(tmpfile.getvalue()).decode('utf-8')
    tmpfile.close()

    user = [[t['user_id'],t['user_id__count'],list(tweet_tag.filter(user_id=t['user_id']).aggregate(Max('like_count'),Max('retweet_count'),Max('reply_count')).values())] for t in tweet_tag.values('user_id').annotate(Count('user_id'))]

    konteks         = {
        'isu_id'        : id,
        'user'          : user,
        'nama_hashtag'  : nama,
        'wordcloud'     : graphic,
        'data_lokasi'   : data_provinsi,
        'tweet_list'    : tweet_tag,
        'map'           : f._repr_html_(),
        'porsi_posisi'  : [nowhere, tweet_tag.count()-nowhere],
        'bulan_list'    : [bulan_list[b.month-1].title() for b in tweet_tag_unf.dates('waktu','month')],
        'bulan1_current': bulan_list[bulan1-1].title(),
        'bulan2_current': bulan_list[bulan2-1].title(),
        'bulan1'        : bulan1,
        'bulan2'        : bulan2,
        'tahun_list'    : [t.year for t in tweet_tag_unf.dates('waktu','year')],
        'tahun_current' : tahun,
        'line_data'     : line_data
    }

    return render(request, 'analysis.html', konteks)

show/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django_pandas.io import read_frame
from stream_tweet.models import TweetsModel


def download_data(request, id, nama, bulan1, bulan2, tahun):
    bulan_list = ['januari', 'februari', 'maret', 'april', 'mei', 'juni',
                  'juli', 'agustus', 'september', 'oktober', 'november', 'desember']

    if nama != 'all':
        tweet_tag = TweetsModel.objects.filter(
                        id_isu=id,
                        tags__hashtag=nama,
                        waktu__year=tahun,
                        waktu__month__gte=bulan1,
                        waktu__month__lte=bulan2)
        namafile = f'{nama} {bulan_list[bulan1-1]}-{bulan_list[bulan2-1]} {tahun}'

    else:
        tweet_tag = TweetsModel.objects.filter(id_isu=id)
        namafile = f'{id}'

    df = read_frame(tweet_tag.all())
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename={namafile}.csv'
    df.to_csv(path_or_buf=response, sep=';', index=False, decimal=".")

    return response


def show_data(request, id, nama, bulan1, bulan2, tahun):
    if nama != 'all':
        if bulan1 != 0:
            tweet_tag = TweetsModel.objects.filter(
                            id_isu=id,
                            tags__hashtag=nama,
                            waktu__year=tahun,
                            waktu__month__gte=bulan1,
                            waktu__month__lte=bulan2)
        else:
            tweet_tag = TweetsModel.objects.filter(id_isu=id,tags__hashtag=nama)

    else:
        tweet_tag = TweetsModel.objects.filter(id_isu=id)

    hashtag_list = [', '.join([j.hashtag for j in t.tags.all()]) for t in tweet_tag]
    return render(request, 'show.html', {'data': zip(tweet_tag, hashtag_list), 'r': [id, nama, bulan1, bulan2, tahun]})

templates/analysis.html
{% extends "base.html" %}

{% block judul_halaman %}
  Dasbor - {{nama_hashtag}}
{% endblock %}

{% block ext %}
  <script type='text/javascript' src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">
    google.charts.load('current', {'packages' :['corechart']});

    google.charts.setOnLoadCallback(LineChart);

      function LineChart() {

        var line = new google.visualization.ChartWrapper({
          'chartType': 'LineChart',
          'containerId': 'LineChart',
          'dataTable' : {{line_data|safe}},
          'options' : {
            'width':440,
            'height':215,
            'legend': { 'position': 'top' }
          },
          'view': {'columns': [0,1,2]}
        });

        line.draw();

        AllTweet = function() {
          line.setView({'columns': [0,1,2]});
          line.draw();
        };

        TweetHashtag = function() {
          line.setView({'columns': [0,1,3]});
          line.draw();
        };

        TweetNoHashtag = function() {
          line.setView({'columns': [0,2,4]});
          line.draw();
        };
    }

  </script>
{% endblock %}

{% block bebas %}
  <form method="POST">
    {% csrf_token %}
    <div class="row justify-content-center" style="margin-left:50px; margin-top:-50px">

      <div class="col-md-1">
        <h2></h2><h2></h2><a class="btn btn-info" style="width:90px" href="{% url 'home:detail' isu_id %}">&#8592; Kembali</a>
      </div>

      <div class="form-group col-md-3">
        <label for="bulan1">Dari bulan : </label>
        <select class="form-control" id="bulan1" name="bulan1">
          {% for bln in bulan_list %}
            {% if bln == bulan1_current %}
              <option selected="selected" value={{bln}}>{{bln}}</option>
            {% else %}
              <option value={{bln}}>{{bln}}</option>
            {% endif %}
          {% endfor %}
        </select>
      </div>

      <div class="form-group col-md-3">
        <label for="bulan2">Hingga bulan : </label>
        <select class="form-control" id="bulan2" name="bulan2">
          {% for bln in bulan_list %}
            {% if bln == bulan2_current %}
              <option selected="selected" value={{bln}}>{{bln}}</option>
            {% else %}
              <option value={{bln}}>{{bln}}</option>
            {% endif %}
          {% endfor %}
        </select>
      </div>

      <div class="form-group col-md-3">
        <label for="tahun">Tahun : </label>
        <select class="form-control" id="tahun" name="tahun">
          {% for thn in tahun_list %}
            {% if thn == tahun_current %}
              <option selected="selected" value={{thn}}>{{thn}}</option>
            {% else %}
              <option value={{thn}}>{{thn}}</option>
            {% endif %}
          {% endfor %}
        </select>
      </div>

      <div class="col-md-1">
        <h2></h2><h2></h2><button type="submit" class="btn btn-dark">Filter</button>
      </div>

    </div>

  </form>


  <div class="row" style="margin-left:1px">

    <div class="col-4">
      <table>
        <tbody>
          <tr>
            <td><button type="button" class="btn btn-outline-primary" onclick="AllTweet()" style="width:110px">Semua Tweet</button></td>
            <td><button type="button" class="btn btn-outline-primary" onclick="TweetHashtag()" style="width:170px">Tweet Dengan Hashtag</button></td>
            <td><button type="button" class="btn btn-outline-primary" onclick="TweetNoHashtag()" style="width:160px">Tweet Tanpa Hashtag</button></td>
          </tr>
          <tr><td colspan="3"><div id="LineChart" style="border:1px solid"></div></td></tr>
        </tbody>
      </table>
    </div>

    <div class="col-3">
      <div class="container bg-info" style="border:1px solid; height:254px; width:341px">
        <div id="TweetList" class="carousel slide">
          <div class="carousel-inner">
            <div class="carousel-item active" data-interval="3000">
              <div class="row justify-content-center">
                <h1>{{nama_hashtag}}</h1>
              </div>
              <div class="row justify-content-center" style="margin-top:10px">
                <button type="submit" class="btn btn-secondary" onclick="window.open('{% url 'show:show' isu_id nama_hashtag bulan1 bulan2 tahun_current %}','_blank')">Lihat Data</button>
              </div>
              <div class="row justify-content-center" style="margin-top:10px">
                <button type="button" class="btn btn-success" onclick="window.open('{% url 'download' isu_id nama_hashtag bulan1 bulan2 tahun_current %}')">Download CSV</button>
              </div>
            </div>
            {% for t in tweet_list %}
            <div class="carousel-item" data-interval="6000">
              <div class="row">
                <div class="col">
                  <h2>@{{t.user_id}}</h2>
                  <h3>{{t.waktu}}</h3>
                </div>
              </div>
              <div class="row text-white">
                <div class="col"><br><h5>{{t.teks}}</h5></div>
              </div>
            </div>
            {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#TweetList" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#TweetList" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>

    <div class="col-5" style="margin-top:-10px">
      <img src="data:image/png;base64,{{ wordcloud }}">
    </div>

  </div>

  <div class="row" style="margin-left:3px; margin-top:10px">

    <div class="col-9">
      {{map|safe}}
    </div>

    <div class="col" style="margin-right:35px">
      <table class="table table-bordered">
        <thead class="thead-light">
          <tr>
            <th scope="col">Keterangan Lokasi Tweet</th>
            <th scope="col">Jumlah</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Tweet tanpa lokasi</td>
            <td style="text-align:center">{{porsi_posisi.1}}</td>
          </tr>
          <tr data-toggle="tooltip" title="{{ data_lokasi|length }} provinsi berbeda" data-placement="bottom">
            <td><span data-toggle="popover" role="button" data-html="true"
                  data-content="
                    {% for key, value in data_lokasi.items %}
                      {{key}},
                    {% endfor %}">Tweet dengan lokasi</span></td>
            <td style="text-align:center">{{porsi_posisi.0}}</td>
          </tr>
        </tbody>
      </table>

      <table id="users_analysis" class="table table-bordered table-sm">
        <thead class="thead-light">
          <tr>
            <th scope="col">User</th>
            <th scope="col">Jumlah</th>
          </tr>
        </thead>
        <tbody>
          {% for usr, jum, att in user %}
          <tr>
            <td>
              <span title="most like {{att.0}} | most retweeted {{att.1}} | most replied {{att.2}}">
                @{{usr}}
              </span>
            </td>
            <td style="text-align:center">{{jum}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

  </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block judul_halaman %}

		{% endblock judul_halaman %}
	</title>
	{% include "snippets/styles.html" %}
	{% block ext %}

	{% endblock %}

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand">Tweet Hashtag Analysis</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:home' 1 %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Buat
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'stream_tweet:online' %}">online</a>
          <a class="dropdown-item" href="{% url 'stream_tweet:file' %}">offline / file</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:manage' %}">atur</a>
      </li>
  </div>
  </nav>

	<div class="container" style="margin-top:50px">
		{% block isi %}

		{% endblock isi %}
	</div>
	{% block bebas %}

	{% endblock %}
	{% include "snippets/scripts.html" %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block judul_halaman %}
  {{judul}}
{% endblock judul_halaman %}

{% block isi %}
  <p>{{isi}}</p>
{% endblock isi %}

templates/show.html
{% extends "base.html" %}

{% block judul_halaman %}
  Show Data
{% endblock %}

{% block bebas %}
<div class="" style='padding-left:10px; padding-right:10px; padding-bottom:10px; margin-top:-40px'>
  <button type="button" class="btn btn-success" onclick="window.open('{% url 'download' r.0 r.1 r.2 r.3 r.4 %}')">Download CSV</button>
  <table id="show_data" class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>User</th>
        <th>User_ID</th>
        <th>Teks</th>
        <th>Reply</th>
        <th>Retweet</th>
        <th>Like</th>
        <th>Waktu</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Lokasi</th>
        <th>Hashtag</th>
      </tr>
    </thead>
    <tbody>
      {% for tweet, hashtag in data %}
      <tr>
        <th>{{forloop.counter}}</th>
        <td>{{tweet.user}}</td>
        <td>@{{tweet.user_id}}</td>
        <td>{{tweet.teks}}</td>
        <td style="text-align:center">{{tweet.reply_count}}</td>
        <td style="text-align:center">{{tweet.retweet_count}}</td>
        <td style="text-align:center">{{tweet.like_count}}</td>
        <td>{{tweet.waktu}}</td>
        <td>{{tweet.latitude}}</td>
        <td>{{tweet.longitude}}</td>
        <td>{{tweet.lokasi}}</td>
        <td>{{hashtag}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}